language: android
dist: trusty
sudo: false
jdk: oraclejdk8

env:
  global:
    - ANDROID_API=30
    - ANDROID_BUILD_TOOLS=29.0.3

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - '.+'
